version: 2
jobs:
  build:
    docker:
      - image: 'rust:1.26.0'
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          keys:
            - >-
              cache-key-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum
              "Cargo.lock" }}
      - run:
          name: Install dependencies
          command: |
            apt-get update && apt-get install -y libusb-1.0-0-dev
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            sudo /opt/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            sudo /opt/google-cloud-sdk/bin/gcloud config set project $GCLOUD_PROJECT
      - run:
          name: Run tests
          command: cargo test
      - save_cache:
          name: Save cache
          paths:
            - ~/.cargo
            - ~/app/target
          key: >-
            cache-key-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum
            "Cargo.lock" }}
