version: 2
references:
  master_br: &master_br
    only:
      - master
  build_env: &build_env
    machine: true
  prepare: &prepare
    run:
      name: Setup global dependencies
      command: |
        sudo apt-get update
        sudo apt-get install -y google-cloud-sdk
        gcloud config set core/disable_usage_reporting true
        gcloud config set component_manager/disable_update_check true
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        gcloud --version
        docker --version
        echo $GOOGLE_CLOUD_PLATFORM_API_KEY > ${HOME}/gcloud-service-key.json
  build_server: &build_server
    run:
      name: Build server container image
      command: make server/build
  test: &test
    run:
      name: Run tests
      command: $HOME/.cargo/bin/cargo test

jobs:
  make_server:
    <<: *build_env
    steps:
      - checkout
      - *prepare
      - *build_server
  do_test:
    <<: *build_env
    steps:
      - checkout
      - *prepare
      - *test

workflows:
  version: 2
  ordinary_workflow:
    jobs:
      - make_server:
          filters:
            branches: *master_br
      - do_test
